/**
 * Gouly frame layer. Every command travels base64 encoded on Tuya DP 101
 * (the Python bridge does the Tuya and base64 layers):
 *   <header> <command> <payload...> <crc>
 * header 0xAA = command (the controller echoes every command it accepts),
 * header 0xBB = report generated by the controller.
 * crc = CRC-8/MAXIM over all preceding bytes.
 */

export const HEADER_COMMAND = 0xaa;
export const HEADER_REPORT = 0xbb;

/** Short commands are zero padded to this length (header and CRC included). */
export const MIN_FRAME_LENGTH = 11;

export class FrameError extends Error {}

export function crc8Maxim(data: Uint8Array): number {
  let crc = 0;
  for (const byte of data) {
    crc ^= byte;
    for (let i = 0; i < 8; i++) {
      crc = crc & 1 ? (crc >> 1) ^ 0x8c : crc >> 1;
    }
  }
  return crc;
}

/**
 * Build a command frame. Without an explicit length the frame is padded to
 * MIN_FRAME_LENGTH, or left at its natural length when the payload is longer
 * (pattern frames are variable length and never padded).
 */
export function buildFrame(command: number, payload: Uint8Array = new Uint8Array(), length?: number): Buffer {
  const natural = 2 + payload.length + 1;
  const total = length ?? Math.max(MIN_FRAME_LENGTH, natural);
  if (natural > total) {
    throw new FrameError(`payload too long for a ${total} byte frame`);
  }
  const frame = Buffer.alloc(total);
  frame[0] = HEADER_COMMAND;
  frame[1] = command;
  frame.set(payload, 2);
  frame[total - 1] = crc8Maxim(frame.subarray(0, total - 1));
  return frame;
}

export function verifyFrame(frame: Uint8Array): void {
  if (frame.length < 3) {
    throw new FrameError('frame too short');
  }
  if (frame[0] !== HEADER_COMMAND && frame[0] !== HEADER_REPORT) {
    throw new FrameError(`unknown header 0x${frame[0].toString(16)}`);
  }
  if (crc8Maxim(frame.subarray(0, frame.length - 1)) !== frame[frame.length - 1]) {
    throw new FrameError('checksum mismatch');
  }
}

export const toHex = (bytes: Uint8Array): string =>
  Buffer.from(bytes).toString('hex').replace(/(..)(?!$)/g, '$1 ');
export const fromHex = (hex: string): Buffer => Buffer.from(hex.replace(/[^0-9a-fA-F]/g, ''), 'hex');

/** What a driver learned from one frame (command echo or controller report). */
export interface StateUpdate {
  on?: boolean;
  brightness?: number; // 0-255
  rgbw?: [number, number, number, number];
  pattern?: Buffer; // pattern body: command byte onward, header and CRC excluded
  speed?: number;
  /** Controller configuration from the state report. */
  info?: { pixels: number; icType: number; rgbOrder: number };
}

/** One controller family's command set. */
export interface Driver {
  readonly kind: 'classic' | 'pro';
  power(on: boolean): Buffer[];
  brightness(value: number): Buffer[];
  colour(r: number, g: number, b: number, w: number): Buffer[];
  /** Replay a recorded pattern body. Absent when the driver cannot replay patterns. */
  pattern?(body: Buffer): Buffer[];
  query(): Buffer[];
  /** Frames that save the current state (sent once after a batch), if the family has one. */
  commit?(): Buffer[];
  parse(frame: Buffer): StateUpdate;
}

export const clampByte = (v: number): number => Math.max(0, Math.min(255, Math.round(v)));
